/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['class', 'class'],
  theme: {
  	extend: {
  		colors: {
  			primary: {
  				'50': '#EFF6FF',
  				'100': '#DBEAFE',
  				'200': '#BFDBFE',
  				'300': '#93C5FD',
  				'400': '#60A5FA',
  				'500': '#3B82F6',
  				'600': '#2563EB',
  				'700': '#1D4ED8',
  				'800': '#1E40AF',
  				'900': '#1E3A8A',
  				'950': '#0B1E4B',
  				DEFAULT: 'hsl(var(--primary))',
  				foreground: 'hsl(var(--primary-foreground))'
  			},
  			secondary: {
  				'50': '#f8fafc',
  				'100': '#f1f5f9',
  				'200': '#e2e8f0',
  				'300': '#cbd5e1',
  				'400': '#94a3b8',
  				'500': '#64748b',
  				'600': '#475569',
  				'700': '#334155',
  				'800': '#1e293b',
  				'900': '#0f172a',
  				'950': '#020617',
  				DEFAULT: 'hsl(var(--secondary))',
  				foreground: 'hsl(var(--secondary-foreground))'
  			},
  			'text-heading': '#111827',
  			'text-body': '#4B5563',
  			'text-muted': '#6B7280',
  			'text-placeholder': '#9CA3AF',
  			'text-link': '#3B82F6',
  			'text-link-hover': '#2563EB',
  			'page-bg': '#F0F8FF',
  			'card-bg': '#FFFFFF',
  			'card-fg': '#111827',
  			'card-border': '#E5E7EB',
  			'card-tint': '#EAF2FF',
  			'elevated-bg': '#FAFAFB',
  			overlay: 'rgba(17,24,39,0.6)',
  			'border-default': '#E5E7EB',
  			'border-divider': '#E4E4E7',
  			'border-focus': '#3B82F6',
  			'field-bg': '#FFFFFF',
  			'field-fg': '#171717',
  			'field-border': '#D4D4D4',
  			'field-placeholder': '#A3A3A3',
  			'field-focus-ring': '#60A5FA',
  			'brand-100': '#DBEAFE',
  			'brand-400': '#60A5FA',
  			'brand-500': '#3B82F6',
  			'brand-600': '#2563EB',
  			'btn-solid-bg': '#3B82F6',
  			'btn-solid-fg': '#FFFFFF',
  			'btn-solid-hover': '#2563EB',
  			'btn-outline-border': '#3B82F6',
  			'btn-outline-fg': '#2563EB',
  			'btn-ghost-fg': '#2563EB',
  			'table-bg': '#FFFFFF',
  			'table-fg': '#111827',
  			'table-border': '#E5E7EB',
  			'table-row-hover': '#F8FAFC',
  			'table-header-bg': '#F1F5F9',
  			'header-bg': '#FFFFFF',
  			'header-fg': '#111827',
  			'header-border': '#E5E7EB',
  			'header-link': '#2563EB',
  			'header-link-hover': '#3B82F6',
  			'header-btn-solid-bg': '#3B82F6',
  			'header-btn-solid-fg': '#FFFFFF',
  			'header-btn-solid-hover': '#2563EB',
  			'header-btn-outline-border': '#3B82F6',
  			'header-btn-outline-fg': '#2563EB',
  			'bg-page': '#F4F4F5',
  			'bg-card': '#FFFFFF',
  			'bg-elevated': '#FAFAFB',
  			'bg-tint': '#EAF2FF',
  			'bg-overlay': 'rgba(17,24,39,0.6)',
  			'input-bg': '#FFFFFF',
  			'input-border': '#D4D4D4',
  			'input-border-focus': '#3B82F6',
  			'input-text': '#171717',
  			'input-placeholder': '#A3A3A3',
  			'status-success': '#16A34A',
  			'status-warning': '#F59E0B',
  			'status-error': '#EF4444',
  			'status-info': '#2563EB',
  			'hover-bg': '#F5F5F5',
  			'active-bg': '#E5E5E5',
  			white: '#FFFFFF',
  			black: '#000000',
  			'header-text': '#FFFFFF',
  			background: 'hsl(var(--background))',
  			foreground: 'hsl(var(--foreground))',
  			card: {
  				DEFAULT: 'hsl(var(--card))',
  				foreground: 'hsl(var(--card-foreground))'
  			},
  			popover: {
  				DEFAULT: 'hsl(var(--popover))',
  				foreground: 'hsl(var(--popover-foreground))'
  			},
  			muted: {
  				DEFAULT: 'hsl(var(--muted))',
  				foreground: 'hsl(var(--muted-foreground))'
  			},
  			accent: {
  				DEFAULT: 'hsl(var(--accent))',
  				foreground: 'hsl(var(--accent-foreground))'
  			},
  			destructive: {
  				DEFAULT: 'hsl(var(--destructive))',
  				foreground: 'hsl(var(--destructive-foreground))'
  			},
  			border: 'hsl(var(--border))',
  			input: 'hsl(var(--input))',
  			ring: 'hsl(var(--ring))',
  			chart: {
  				'1': 'hsl(var(--chart-1))',
  				'2': 'hsl(var(--chart-2))',
  				'3': 'hsl(var(--chart-3))',
  				'4': 'hsl(var(--chart-4))',
  				'5': 'hsl(var(--chart-5))'
  			}
  		},
  		borderRadius: {
  			lg: 'var(--radius)',
  			md: 'calc(var(--radius) - 2px)',
  			sm: 'calc(var(--radius) - 4px)'
  		}
  	}
  },
  plugins: [require("tailwindcss-animate")],
};
